prj2: Node.hpp Node.cpp BST.hpp BST.cpp bubbleSort.cpp bubbleSort.hpp insertionSort.cpp insertionSort.hpp shellSort.cpp shellSort.hpp quickSort.cpp quickSort.hpp selectionSort.cpp structData.hpp main.cpp
	g++ -Wall Node.cpp BST.cpp bubbleSort.cpp insertionSort.cpp shellSort.cpp quickSort.cpp selectionSort.cpp main.cpp -o prj2
	./prj2